services:
  server1:
    build: ./server1
    container_name: server1
    ports:
      - "5000:5000"

  server2:
    build: ./server2
    container_name: server2
    ports:
      - "5001:5000"

  dashboard:
    image: nginx:alpine
    container_name: dashboard
    volumes:
      - ./dashboard:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
