version: "3.9"
services:
  server1:
    build: ./server
    container_name: server1
    ports:
      - "5000:5000"
      - "50051:50051"
  
  server2:
    build: ./server
    container_name: server2
    ports:
      - "5001:5000"
      - "50052:50051"
    deploy:
      replicas: 0   # awalnya tidak jalan
