apiVersion: v1
kind: Service
metadata:
  name: server1-svc
spec:
  selector:
    app: server1
  type: NodePort
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30000
    - name: grpc
      port: 50051
      targetPort: 50051
      nodePort: 30001
